COMANDO BÁSICO DE SQL.

USUADO PROGRAMA MySQL

NOME BANCO: ISISSEGURO

PARA INICIAR O BANCO
USE `isisseguro`;

SELECIONAR TABELA
select * from 

MODIFICAR TABELA
ALTER TABLE ###### 
MODIFY COLUMN ####### VARCHAR(9);

ADICIONAR CAMPO
ALTER TABLE #########
ADD COLUMN ########### VARCHAR(60) COMMENT 'NOME FANTASIA EMPRESA',

INSERIR DADOS NA TABELA
INSERT INTO `ISISSEGURO`.`###TABELA####` (`###TELA_NOME###`) 
VALUES ('###VALOR###')
exemplo:
INSERT INTO `isisseguro`.`CAD_USUARIO` (`USU_NOME` , `USU_STATUS` , `USU_DATACAD` , `USU_EMAIL` ,`USU_SENHA` , `USU_SENHAC`)
VALUES ('Emerson de Carvalho','A','2025-06-12','emersoncarvalho@hotmail.com.br',123,123)




-- Cadastro de Usuário

CREATE TABLE CAD_USUARIO(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY COMMENT 'CÓDIGO USUARIO',
    USU_NOME VARCHAR(200) COMMENT 'NOME DE USUÁRIO',
    USU_STATUS CHAR(1) COMMENT 'USUÁRIO ATIVO E INATIVO',
    USU_DATACAD DATE COMMENT 'DATA CADASTRO',
    USU_EMAIL VARCHAR(200) COMMENT 'EMAIL DE CADASTRO',
    USU_SENHA VARCHAR(20) COMMENT 'SENHA ACESSO',
    USU_SENHAC VARCHAR(20) COMMENT 'SENHA ACESSO'
) COMMENT 'DESCRIÇÃO DA TABELA CAD_USUARIO';





/*Uso do Site da Isis*/

USE `isisseguro`;

CREATE TABLE CAD_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY COMMENT 'CÓDIGO USUARIO',
    USU_NOME VARCHAR(200) COMMENT 'NOME DE USUÁRIO',
    USU_STATUS CHAR(1) COMMENT 'USUÁRIO ATIVO E INATIVO',
    USU_DATACAD DATE COMMENT 'DATA CADASTRO',
    USU_EMAIL VARCHAR(200) COMMENT 'EMAIL DE CADASTRO',
    USU_SENHA VARCHAR(20) COMMENT 'SENHA ACESSO',
    USU_SENHAC VARCHAR(20) COMMENT 'SENHA ACESSO'
) COMMENT 'DESCRIÇÃO DA TABELA CAD_USUARIO';

SELECT * FROM CAD_USUARIO;

INSERT INTO `isisseguro`.`CAD_USUARIO` (`USU_NOME` , `USU_STATUS` , `USU_DATACAD` , `USU_EMAIL` ,`USU_SENHA` , `USU_SENHAC`)
VALUES ('Emerson de Carvalho','A','2025-06-12','emersoncarvalho@hotmail.com.br',123,123);

DELETE FROM CAD_USUARIO WHERE ID_USUARIO = 1 ;

ALTER TABLE CAD_USUARIO 
MODIFY USU_SENHA VARCHAR(255),
MODIFY USU_SENHAC VARCHAR(255);
