CREATE TABLE CAD_SEGURADORA(
    ID_SEGURADORA INT AUTO_INCREMENT PRIMARY KEY COMMENT 'CÓDIGO SEGURADORA',
    SEG_SEGURADORA VARCHAR(200) COMMENT 'NOME DA SEGURADORA',
    SEG_STATUS CHAR(1) COMMENT 'SEGURADORA (A)TIVO E (I)NATIVO',
    SEG_DATACAD DATE COMMENT 'DATA CADASTRO',
) COMMENT 'DESCRIÇÃO DA TABELA CAD_SEGURADORA';