CREATE TABLE CAD_CLIENTE(
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY COMMENT 'CÓDIGO CLIENTE',
    CLI_RAZAO VARCHAR(200) COMMENT 'NOME DA RAZÃO CLIENTE',
    CLI_FANTASIA VARCHAR(200) COMMENT 'NOME DA FANTASIA CLIENTE',

    CLI_CPNJ VARCHAR(50) COMMENT 'CIDADE CLIENTE',
    CLI_IE VARCHAR(50) COMMENT 'CIDADE CLIENTE',

    CLI_CPF VARCHAR(50) COMMENT 'CIDADE CLIENTE',
    CLI_RG VARCHAR(50) COMMENT 'CIDADE CLIENTE',

    CLI_ENDERECO VARCHAR(200) COMMENT 'ENDEREÇO CLIENTE',
    CLI_NUMERO VARCHAR(20) COMMENT 'NUMERO CLIENTE',
    CLI_COMPLEMENTO VARCHAR(40) COMMENT 'COMPLEMENTO CLIENTE',
    CLI_BAIRRO VARCHAR(40) COMMENT 'BAIRRO CLIENTE',
    CLI_CIDADE VARCHAR(50) COMMENT 'CIDADE CLIENTE',
    CLI_UF CHAR(2) COMMENT 'ESTADO CLIENTE',
    CLI_CEP VARCHAR(7) COMMENT 'CEP CLIENTE',





    SEG_STATUS CHAR(1) COMMENT 'SEGURADORA (A)TIVO E (I)NATIVO',
    SEG_DATACAD DATE COMMENT 'DATA CADASTRO',
) COMMENT 'DESCRIÇÃO DA TABELA CAD_SEGURADORA';